<div id="keyboard-slider" class="ui-keyboard ui-widget keyboard-slider keyboard-class" role="textbox">
                          <div name="default" class="ui-keyboard-keyset ui-keyboard-keyset-default" style="display: block;">
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-113 ui-state-default ui-corner-all" data-value="q" name="113" data-pos="0,0" title="" data-action="q" data-original="q" data-curtxt="q" data-curnum="0"><span>q</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-119 ui-state-default ui-corner-all" data-value="w" name="119" data-pos="0,1" title="" data-action="w" data-original="w" data-curtxt="w" data-curnum="0"><span>w</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-101 ui-state-default ui-corner-all" data-value="e" name="101" data-pos="0,2" title="" data-action="e" data-original="e" data-curtxt="e" data-curnum="0"><span>e</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-114 ui-state-default ui-corner-all" data-value="r" name="114" data-pos="0,3" title="" data-action="r" data-original="r" data-curtxt="r" data-curnum="0"><span>r</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-116 ui-state-default ui-corner-all" data-value="t" name="116" data-pos="0,4" title="" data-action="t" data-original="t" data-curtxt="t" data-curnum="0"><span>t</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-121 ui-state-default ui-corner-all" data-value="y" name="121" data-pos="0,5" title="" data-action="y" data-original="y" data-curtxt="y" data-curnum="0"><span>y</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-117 ui-state-default ui-corner-all" data-value="u" name="117" data-pos="0,6" title="" data-action="u" data-original="u" data-curtxt="u" data-curnum="0"><span>u</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-105 ui-state-default ui-corner-all" data-value="i" name="105" data-pos="0,7" title="" data-action="i" data-original="i" data-curtxt="i" data-curnum="0"><span>i</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-111 ui-state-default ui-corner-all" data-value="o" name="111" data-pos="0,8" title="" data-action="o" data-original="o" data-curtxt="o" data-curnum="0"><span>o</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-112 ui-state-default ui-corner-all" data-value="p" name="112" data-pos="0,9" title="" data-action="p" data-original="p" data-curtxt="p" data-curnum="0"><span>p</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-bksp ui-keyboard-actionkey ui-state-default ui-corner-all" data-value="←" name="bksp" data-pos="0,10" title="" data-action="bksp" data-original="←" data-curtxt="←" data-curnum="0"><span>←</span></button>
                            <br class="ui-keyboard-button-endrow">
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-97 ui-state-default ui-corner-all" data-value="a" name="97" data-pos="1,0" title="" data-action="a" data-original="a" data-curtxt="a" data-curnum="0"><span>a</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-115 ui-state-default ui-corner-all" data-value="s" name="115" data-pos="1,1" title="" data-action="s" data-original="s" data-curtxt="s" data-curnum="0"><span>s</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-100 ui-state-default ui-corner-all" data-value="d" name="100" data-pos="1,2" title="" data-action="d" data-original="d" data-curtxt="d" data-curnum="0"><span>d</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-102 ui-state-default ui-corner-all" data-value="f" name="102" data-pos="1,3" title="" data-action="f" data-original="f" data-curtxt="f" data-curnum="0"><span>f</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-103 ui-state-default ui-corner-all" data-value="g" name="103" data-pos="1,4" title="" data-action="g" data-original="g" data-curtxt="g" data-curnum="0"><span>g</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-104 ui-state-default ui-corner-all" data-value="h" name="104" data-pos="1,5" title="" data-action="h" data-original="h" data-curtxt="h" data-curnum="0"><span>h</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-106 ui-state-default ui-corner-all" data-value="j" name="106" data-pos="1,6" title="" data-action="j" data-original="j" data-curtxt="j" data-curnum="0"><span>j</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-107 ui-state-default ui-corner-all" data-value="k" name="107" data-pos="1,7" title="" data-action="k" data-original="k" data-curtxt="k" data-curnum="0"><span>k</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-108 ui-state-default ui-corner-all" data-value="l" name="108" data-pos="1,8" title="" data-action="l" data-original="l" data-curtxt="l" data-curnum="0"><span>l</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-enter ui-keyboard-widekey ui-keyboard-actionkey ui-state-default ui-corner-all ui-state-active" data-value="Enter" name="enter" data-pos="1,9" title="Enter ⏎" data-action="enter" data-original="Enter" data-curtxt="Enter" data-curnum="0"><span>Enter</span></button>
                            <br class="ui-keyboard-button-endrow">
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-shift ui-keyboard-actionkey ui-state-default ui-corner-all" data-value="⇧" name="shift" data-pos="2,0" title="Shift" data-action="shift" data-original="⇧" data-curtxt="⇧" data-curnum="0"><span>⇧</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-122 ui-state-default ui-corner-all" data-value="z" name="122" data-pos="2,1" title="" data-action="z" data-original="z" data-curtxt="z" data-curnum="0"><span>z</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-120 ui-state-default ui-corner-all" data-value="x" name="120" data-pos="2,2" title="" data-action="x" data-original="x" data-curtxt="x" data-curnum="0"><span>x</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-99 ui-state-default ui-corner-all" data-value="c" name="99" data-pos="2,3" title="" data-action="c" data-original="c" data-curtxt="c" data-curnum="0"><span>c</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-118 ui-state-default ui-corner-all" data-value="v" name="118" data-pos="2,4" title="" data-action="v" data-original="v" data-curtxt="v" data-curnum="0"><span>v</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-98 ui-state-default ui-corner-all" data-value="b" name="98" data-pos="2,5" title="" data-action="b" data-original="b" data-curtxt="b" data-curnum="0"><span>b</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-110 ui-state-default ui-corner-all" data-value="n" name="110" data-pos="2,6" title="" data-action="n" data-original="n" data-curtxt="n" data-curnum="0"><span>n</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-109 ui-state-default ui-corner-all" data-value="m" name="109" data-pos="2,7" title="" data-action="m" data-original="m" data-curtxt="m" data-curnum="0"><span>m</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-44 ui-state-default ui-corner-all" data-value="," name="44" data-pos="2,8" title="" data-action="," data-original="," data-curtxt="," data-curnum="0"><span>,</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-46 ui-state-default ui-corner-all" data-value="." name="46" data-pos="2,9" title="" data-action="." data-original="." data-curtxt="." data-curnum="0"><span>.</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-shift ui-keyboard-actionkey ui-state-default ui-corner-all" data-value="⇧" name="shift" data-pos="2,10" title="Shift" data-action="shift" data-original="⇧" data-curtxt="⇧" data-curnum="0"><span>⇧</span></button>
                            <br class="ui-keyboard-button-endrow">
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-meta1 ui-keyboard-widekey ui-keyboard-actionkey ui-state-default ui-corner-all" data-value="123" name="meta1" data-pos="3,0" title="" data-action="meta1" data-original="123" data-curtxt="123" data-curnum="0"><span>123</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-space ui-keyboard-widekey ui-keyboard-actionkey ui-state-default ui-corner-all" data-value="&amp;nbsp;" name="space" data-pos="3,1" title="Space" data-action="space" data-original="&amp;nbsp;" data-curtxt="&amp;nbsp;" data-curnum="0"><span>&nbsp;</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-cancel ui-keyboard-widekey ui-keyboard-actionkey ui-state-default ui-corner-all ui-state-active" data-value="Cancel" name="cancel" data-pos="3,2" title="Cancel" data-action="cancel" data-original="Cancel" data-curtxt="Cancel" data-curnum="0"><span>Cancel</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-accept ui-keyboard-widekey ui-keyboard-actionkey ui-state-default ui-corner-all ui-state-active" data-value="return" name="accept" data-pos="3,3" title="" data-action="accept" data-original="return" data-curtxt="return" data-curnum="0"><span>return</span></button>
                            <br class="ui-keyboard-button-endrow">
                          </div>
                          <div name="shift" class="ui-keyboard-keyset ui-keyboard-keyset-shift" style="display: none;">
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-81 ui-state-default ui-corner-all" data-value="Q" name="81" data-pos="0,0" title="" data-action="Q" data-original="Q" data-curtxt="Q" data-curnum="0"><span>Q</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-87 ui-state-default ui-corner-all" data-value="W" name="87" data-pos="0,1" title="" data-action="W" data-original="W" data-curtxt="W" data-curnum="0"><span>W</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-69 ui-state-default ui-corner-all" data-value="E" name="69" data-pos="0,2" title="" data-action="E" data-original="E" data-curtxt="E" data-curnum="0"><span>E</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-82 ui-state-default ui-corner-all" data-value="R" name="82" data-pos="0,3" title="" data-action="R" data-original="R" data-curtxt="R" data-curnum="0"><span>R</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-84 ui-state-default ui-corner-all" data-value="T" name="84" data-pos="0,4" title="" data-action="T" data-original="T" data-curtxt="T" data-curnum="0"><span>T</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-89 ui-state-default ui-corner-all" data-value="Y" name="89" data-pos="0,5" title="" data-action="Y" data-original="Y" data-curtxt="Y" data-curnum="0"><span>Y</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-85 ui-state-default ui-corner-all" data-value="U" name="85" data-pos="0,6" title="" data-action="U" data-original="U" data-curtxt="U" data-curnum="0"><span>U</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-73 ui-state-default ui-corner-all" data-value="I" name="73" data-pos="0,7" title="" data-action="I" data-original="I" data-curtxt="I" data-curnum="0"><span>I</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-79 ui-state-default ui-corner-all" data-value="O" name="79" data-pos="0,8" title="" data-action="O" data-original="O" data-curtxt="O" data-curnum="0"><span>O</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-80 ui-state-default ui-corner-all" data-value="P" name="80" data-pos="0,9" title="" data-action="P" data-original="P" data-curtxt="P" data-curnum="0"><span>P</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-bksp ui-keyboard-actionkey ui-state-default ui-corner-all" data-value="←" name="bksp" data-pos="0,10" title="" data-action="bksp" data-original="←" data-curtxt="←" data-curnum="0"><span>←</span></button>
                            <br class="ui-keyboard-button-endrow">
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-65 ui-state-default ui-corner-all" data-value="A" name="65" data-pos="1,0" title="" data-action="A" data-original="A" data-curtxt="A" data-curnum="0"><span>A</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-83 ui-state-default ui-corner-all" data-value="S" name="83" data-pos="1,1" title="" data-action="S" data-original="S" data-curtxt="S" data-curnum="0"><span>S</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-68 ui-state-default ui-corner-all" data-value="D" name="68" data-pos="1,2" title="" data-action="D" data-original="D" data-curtxt="D" data-curnum="0"><span>D</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-70 ui-state-default ui-corner-all" data-value="F" name="70" data-pos="1,3" title="" data-action="F" data-original="F" data-curtxt="F" data-curnum="0"><span>F</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-71 ui-state-default ui-corner-all" data-value="G" name="71" data-pos="1,4" title="" data-action="G" data-original="G" data-curtxt="G" data-curnum="0"><span>G</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-72 ui-state-default ui-corner-all" data-value="H" name="72" data-pos="1,5" title="" data-action="H" data-original="H" data-curtxt="H" data-curnum="0"><span>H</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-74 ui-state-default ui-corner-all" data-value="J" name="74" data-pos="1,6" title="" data-action="J" data-original="J" data-curtxt="J" data-curnum="0"><span>J</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-75 ui-state-default ui-corner-all" data-value="K" name="75" data-pos="1,7" title="" data-action="K" data-original="K" data-curtxt="K" data-curnum="0"><span>K</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-76 ui-state-default ui-corner-all" data-value="L" name="76" data-pos="1,8" title="" data-action="L" data-original="L" data-curtxt="L" data-curnum="0"><span>L</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-enter ui-keyboard-widekey ui-keyboard-actionkey ui-state-default ui-corner-all ui-state-active" data-value="Enter" name="enter" data-pos="1,9" title="Enter ⏎" data-action="enter" data-original="Enter" data-curtxt="Enter" data-curnum="0"><span>Enter</span></button>
                            <br class="ui-keyboard-button-endrow">
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-shift ui-keyboard-actionkey ui-state-default ui-corner-all" data-value="⇧" name="shift" data-pos="2,0" title="Shift" data-action="shift" data-original="⇧" data-curtxt="⇧" data-curnum="0"><span>⇧</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-90 ui-state-default ui-corner-all" data-value="Z" name="90" data-pos="2,1" title="" data-action="Z" data-original="Z" data-curtxt="Z" data-curnum="0"><span>Z</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-88 ui-state-default ui-corner-all" data-value="X" name="88" data-pos="2,2" title="" data-action="X" data-original="X" data-curtxt="X" data-curnum="0"><span>X</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-67 ui-state-default ui-corner-all" data-value="C" name="67" data-pos="2,3" title="" data-action="C" data-original="C" data-curtxt="C" data-curnum="0"><span>C</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-86 ui-state-default ui-corner-all" data-value="V" name="86" data-pos="2,4" title="" data-action="V" data-original="V" data-curtxt="V" data-curnum="0"><span>V</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-66 ui-state-default ui-corner-all" data-value="B" name="66" data-pos="2,5" title="" data-action="B" data-original="B" data-curtxt="B" data-curnum="0"><span>B</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-78 ui-state-default ui-corner-all" data-value="N" name="78" data-pos="2,6" title="" data-action="N" data-original="N" data-curtxt="N" data-curnum="0"><span>N</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-77 ui-state-default ui-corner-all" data-value="M" name="77" data-pos="2,7" title="" data-action="M" data-original="M" data-curtxt="M" data-curnum="0"><span>M</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-47 ui-state-default ui-corner-all" data-value="/" name="47" data-pos="2,8" title="" data-action="/" data-original="/" data-curtxt="/" data-curnum="0"><span>/</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-63 ui-state-default ui-corner-all" data-value="?" name="63" data-pos="2,9" title="" data-action="?" data-original="?" data-curtxt="?" data-curnum="0"><span>?</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-shift ui-keyboard-actionkey ui-state-default ui-corner-all" data-value="⇧" name="shift" data-pos="2,10" title="Shift" data-action="shift" data-original="⇧" data-curtxt="⇧" data-curnum="0"><span>⇧</span></button>
                            <br class="ui-keyboard-button-endrow">
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-meta1 ui-keyboard-widekey ui-keyboard-actionkey ui-state-default ui-corner-all" data-value="123" name="meta1" data-pos="3,0" title="" data-action="meta1" data-original="123" data-curtxt="123" data-curnum="0"><span>123</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-space ui-keyboard-widekey ui-keyboard-actionkey ui-state-default ui-corner-all" data-value="&amp;nbsp;" name="space" data-pos="3,1" title="Space" data-action="space" data-original="&amp;nbsp;" data-curtxt="&amp;nbsp;" data-curnum="0"><span>&nbsp;</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-meta1 ui-keyboard-widekey ui-keyboard-actionkey ui-state-default ui-corner-all" data-value="123" name="meta1" data-pos="3,2" title="" data-action="meta1" data-original="123" data-curtxt="123" data-curnum="0"><span>123</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-accept ui-keyboard-widekey ui-keyboard-actionkey ui-state-default ui-corner-all ui-state-active" data-value="return" name="accept" data-pos="3,3" title="" data-action="accept" data-original="return" data-curtxt="return" data-curnum="0"><span>return</span></button>
                            <br class="ui-keyboard-button-endrow">
                          </div>
                          <div name="meta1" class="ui-keyboard-keyset ui-keyboard-keyset-meta1" style="display: none;">
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-49 ui-state-default ui-corner-all" data-value="1" name="49" data-pos="0,0" title="" data-action="1" data-original="1" data-curtxt="1" data-curnum="0"><span>1</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-50 ui-state-default ui-corner-all" data-value="2" name="50" data-pos="0,1" title="" data-action="2" data-original="2" data-curtxt="2" data-curnum="0"><span>2</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-51 ui-state-default ui-corner-all" data-value="3" name="51" data-pos="0,2" title="" data-action="3" data-original="3" data-curtxt="3" data-curnum="0"><span>3</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-52 ui-state-default ui-corner-all" data-value="4" name="52" data-pos="0,3" title="" data-action="4" data-original="4" data-curtxt="4" data-curnum="0"><span>4</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-53 ui-state-default ui-corner-all" data-value="5" name="53" data-pos="0,4" title="" data-action="5" data-original="5" data-curtxt="5" data-curnum="0"><span>5</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-54 ui-state-default ui-corner-all" data-value="6" name="54" data-pos="0,5" title="" data-action="6" data-original="6" data-curtxt="6" data-curnum="0"><span>6</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-55 ui-state-default ui-corner-all" data-value="7" name="55" data-pos="0,6" title="" data-action="7" data-original="7" data-curtxt="7" data-curnum="0"><span>7</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-56 ui-state-default ui-corner-all" data-value="8" name="56" data-pos="0,7" title="" data-action="8" data-original="8" data-curtxt="8" data-curnum="0"><span>8</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-57 ui-state-default ui-corner-all" data-value="9" name="57" data-pos="0,8" title="" data-action="9" data-original="9" data-curtxt="9" data-curnum="0"><span>9</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-48 ui-state-default ui-corner-all" data-value="0" name="48" data-pos="0,9" title="" data-action="0" data-original="0" data-curtxt="0" data-curnum="0"><span>0</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-bksp ui-keyboard-actionkey ui-state-default ui-corner-all" data-value="←" name="bksp" data-pos="0,10" title="" data-action="bksp" data-original="←" data-curtxt="←" data-curnum="0"><span>←</span></button>
                            <br class="ui-keyboard-button-endrow">
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-45 ui-state-default ui-corner-all" data-value="-" name="45" data-pos="1,0" title="" data-action="-" data-original="-" data-curtxt="-" data-curnum="0"><span>-</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-47 ui-state-default ui-corner-all" data-value="/" name="47" data-pos="1,1" title="" data-action="/" data-original="/" data-curtxt="/" data-curnum="0"><span>/</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-58 ui-state-default ui-corner-all" data-value=":" name="58" data-pos="1,2" title="" data-action=":" data-original=":" data-curtxt=":" data-curnum="0"><span>:</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-59 ui-state-default ui-corner-all" data-value=";" name="59" data-pos="1,3" title="" data-action=";" data-original=";" data-curtxt=";" data-curnum="0"><span>;</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-40 ui-state-default ui-corner-all" data-value="(" name="40" data-pos="1,4" title="" data-action="(" data-original="(" data-curtxt="(" data-curnum="0"><span>(</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-41 ui-state-default ui-corner-all" data-value=")" name="41" data-pos="1,5" title="" data-action=")" data-original=")" data-curtxt=")" data-curnum="0"><span>)</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-8364 ui-state-default ui-corner-all" data-value="€" name="8364" data-pos="1,6" title="" data-action="€" data-original="€" data-curtxt="€" data-curnum="0"><span>€</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-38 ui-state-default ui-corner-all" data-value="&amp;" name="38" data-pos="1,7" title="" data-action="&amp;" data-original="&amp;" data-curtxt="&amp;" data-curnum="0"><span>&amp;</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-64 ui-state-default ui-corner-all" data-value="@" name="64" data-pos="1,8" title="" data-action="@" data-original="@" data-curtxt="@" data-curnum="0"><span>@</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-enter ui-keyboard-widekey ui-keyboard-actionkey ui-state-default ui-corner-all ui-state-active" data-value="Enter" name="enter" data-pos="1,9" title="Enter ⏎" data-action="enter" data-original="Enter" data-curtxt="Enter" data-curnum="0"><span>Enter</span></button>
                            <br class="ui-keyboard-button-endrow">
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-meta2 ui-keyboard-widekey ui-keyboard-actionkey ui-state-default ui-corner-all" data-value="#+=" name="meta2" data-pos="2,0" title="" data-action="meta2" data-original="#+=" data-curtxt="#+=" data-curnum="0"><span>#+=</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-46 ui-state-default ui-corner-all" data-value="." name="46" data-pos="2,1" title="" data-action="." data-original="." data-curtxt="." data-curnum="0"><span>.</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-44 ui-state-default ui-corner-all" data-value="," name="44" data-pos="2,2" title="" data-action="," data-original="," data-curtxt="," data-curnum="0"><span>,</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-63 ui-state-default ui-corner-all" data-value="?" name="63" data-pos="2,3" title="" data-action="?" data-original="?" data-curtxt="?" data-curnum="0"><span>?</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-33 ui-state-default ui-corner-all" data-value="!" name="33" data-pos="2,4" title="" data-action="!" data-original="!" data-curtxt="!" data-curnum="0"><span>!</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-39 ui-state-default ui-corner-all" data-value="'" name="39" data-pos="2,5" title="" data-action="'" data-original="'" data-curtxt="'" data-curnum="0"><span>'</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-34 ui-state-default ui-corner-all" data-value="&quot;" name="34" data-pos="2,6" title="" data-action="&quot;" data-original="&quot;" data-curtxt="&quot;" data-curnum="0"><span>"</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-meta2 ui-keyboard-widekey ui-keyboard-actionkey ui-state-default ui-corner-all" data-value="#+=" name="meta2" data-pos="2,7" title="" data-action="meta2" data-original="#+=" data-curtxt="#+=" data-curnum="0"><span>#+=</span></button>
                            <br class="ui-keyboard-button-endrow">
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-default ui-keyboard-widekey ui-keyboard-actionkey ui-state-default ui-corner-all" data-value="ABC" name="default" data-pos="3,0" title="" data-action="default" data-original="ABC" data-curtxt="ABC" data-curnum="0"><span>ABC</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-space ui-keyboard-widekey ui-keyboard-actionkey ui-state-default ui-corner-all" data-value="&amp;nbsp;" name="space" data-pos="3,1" title="Space" data-action="space" data-original="&amp;nbsp;" data-curtxt="&amp;nbsp;" data-curnum="0"><span>&nbsp;</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-default ui-keyboard-widekey ui-keyboard-actionkey ui-state-default ui-corner-all" data-value="ABC" name="default" data-pos="3,2" title="" data-action="default" data-original="ABC" data-curtxt="ABC" data-curnum="0"><span>ABC</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-accept ui-keyboard-widekey ui-keyboard-actionkey ui-state-default ui-corner-all ui-state-active" data-value="return" name="accept" data-pos="3,3" title="" data-action="accept" data-original="return" data-curtxt="return" data-curnum="0"><span>return</span></button>
                            <br class="ui-keyboard-button-endrow">
                          </div>
                          <div name="meta2" class="ui-keyboard-keyset ui-keyboard-keyset-meta2" style="display: none;">
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-91 ui-state-default ui-corner-all" data-value="[" name="91" data-pos="0,0" title="" data-action="[" data-original="[" data-curtxt="[" data-curnum="0"><span>[</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-93 ui-state-default ui-corner-all" data-value="]" name="93" data-pos="0,1" title="" data-action="]" data-original="]" data-curtxt="]" data-curnum="0"><span>]</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-123 ui-state-default ui-corner-all" data-value="{" name="123" data-pos="0,2" title="" data-action="{" data-original="{" data-curtxt="{" data-curnum="0"><span>{</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-125 ui-state-default ui-corner-all" data-value="}" name="125" data-pos="0,3" title="" data-action="}" data-original="}" data-curtxt="}" data-curnum="0"><span>}</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-35 ui-state-default ui-corner-all" data-value="#" name="35" data-pos="0,4" title="" data-action="#" data-original="#" data-curtxt="#" data-curnum="0"><span>#</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-37 ui-state-default ui-corner-all" data-value="%" name="37" data-pos="0,5" title="" data-action="%" data-original="%" data-curtxt="%" data-curnum="0"><span>%</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-94 ui-state-default ui-corner-all" data-value="^" name="94" data-pos="0,6" title="" data-action="^" data-original="^" data-curtxt="^" data-curnum="0"><span>^</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-42 ui-state-default ui-corner-all" data-value="*" name="42" data-pos="0,7" title="" data-action="*" data-original="*" data-curtxt="*" data-curnum="0"><span>*</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-43 ui-state-default ui-corner-all" data-value="+" name="43" data-pos="0,8" title="" data-action="+" data-original="+" data-curtxt="+" data-curnum="0"><span>+</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-61 ui-state-default ui-corner-all" data-value="=" name="61" data-pos="0,9" title="" data-action="=" data-original="=" data-curtxt="=" data-curnum="0"><span>=</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-bksp ui-keyboard-actionkey ui-state-default ui-corner-all" data-value="←" name="bksp" data-pos="0,10" title="" data-action="bksp" data-original="←" data-curtxt="←" data-curnum="0"><span>←</span></button>
                            <br class="ui-keyboard-button-endrow">
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-95 ui-state-default ui-corner-all" data-value="_" name="95" data-pos="1,0" title="" data-action="_" data-original="_" data-curtxt="_" data-curnum="0"><span>_</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-92 ui-state-default ui-corner-all" data-value="\" name="92" data-pos="1,1" title="" data-action="\" data-original="\" data-curtxt="\" data-curnum="0"><span>\</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-124 ui-state-default ui-corner-all" data-value="|" name="124" data-pos="1,2" title="" data-action="|" data-original="|" data-curtxt="|" data-curnum="0"><span>|</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-38 ui-keyboard-widekey ui-state-default ui-corner-all" data-value="&amp;lt;" name="38" data-pos="1,3" title="" data-action="&amp;lt;" data-original="&amp;lt;" data-curtxt="&amp;lt;" data-curnum="0"><span>&lt;</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-38 ui-keyboard-widekey ui-state-default ui-corner-all" data-value="&amp;gt;" name="38" data-pos="1,4" title="" data-action="&amp;gt;" data-original="&amp;gt;" data-curtxt="&amp;gt;" data-curnum="0"><span>&gt;</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-36 ui-state-default ui-corner-all" data-value="$" name="36" data-pos="1,5" title="" data-action="$" data-original="$" data-curtxt="$" data-curnum="0"><span>$</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-163 ui-state-default ui-corner-all" data-value="£" name="163" data-pos="1,6" title="" data-action="£" data-original="£" data-curtxt="£" data-curnum="0"><span>£</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-165 ui-state-default ui-corner-all" data-value="¥" name="165" data-pos="1,7" title="" data-action="¥" data-original="¥" data-curtxt="¥" data-curnum="0"><span>¥</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-enter ui-keyboard-widekey ui-keyboard-actionkey ui-state-default ui-corner-all ui-state-active" data-value="Enter" name="enter" data-pos="1,8" title="Enter ⏎" data-action="enter" data-original="Enter" data-curtxt="Enter" data-curnum="0"><span>Enter</span></button>
                            <br class="ui-keyboard-button-endrow">
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-meta1 ui-keyboard-widekey ui-keyboard-actionkey ui-state-default ui-corner-all" data-value="123" name="meta1" data-pos="2,0" title="" data-action="meta1" data-original="123" data-curtxt="123" data-curnum="0"><span>123</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-126 ui-state-default ui-corner-all" data-value="~" name="126" data-pos="2,1" title="" data-action="~" data-original="~" data-curtxt="~" data-curnum="0"><span>~</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-46 ui-state-default ui-corner-all" data-value="." name="46" data-pos="2,2" title="" data-action="." data-original="." data-curtxt="." data-curnum="0"><span>.</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-44 ui-state-default ui-corner-all" data-value="," name="44" data-pos="2,3" title="" data-action="," data-original="," data-curtxt="," data-curnum="0"><span>,</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-63 ui-state-default ui-corner-all" data-value="?" name="63" data-pos="2,4" title="" data-action="?" data-original="?" data-curtxt="?" data-curnum="0"><span>?</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-33 ui-state-default ui-corner-all" data-value="!" name="33" data-pos="2,5" title="" data-action="!" data-original="!" data-curtxt="!" data-curnum="0"><span>!</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-39 ui-state-default ui-corner-all" data-value="'" name="39" data-pos="2,6" title="" data-action="'" data-original="'" data-curtxt="'" data-curnum="0"><span>'</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-34 ui-state-default ui-corner-all" data-value="&quot;" name="34" data-pos="2,7" title="" data-action="&quot;" data-original="&quot;" data-curtxt="&quot;" data-curnum="0"><span>"</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-meta1 ui-keyboard-widekey ui-keyboard-actionkey ui-state-default ui-corner-all" data-value="123" name="meta1" data-pos="2,8" title="" data-action="meta1" data-original="123" data-curtxt="123" data-curnum="0"><span>123</span></button>
                            <br class="ui-keyboard-button-endrow">
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-default ui-keyboard-widekey ui-keyboard-actionkey ui-state-default ui-corner-all" data-value="ABC" name="default" data-pos="3,0" title="" data-action="default" data-original="ABC" data-curtxt="ABC" data-curnum="0"><span>ABC</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-space ui-keyboard-widekey ui-keyboard-actionkey ui-state-default ui-corner-all" data-value="&amp;nbsp;" name="space" data-pos="3,1" title="Space" data-action="space" data-original="&amp;nbsp;" data-curtxt="&amp;nbsp;" data-curnum="0"><span>&nbsp;</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-default ui-keyboard-widekey ui-keyboard-actionkey ui-state-default ui-corner-all" data-value="ABC" name="default" data-pos="3,2" title="" data-action="default" data-original="ABC" data-curtxt="ABC" data-curnum="0"><span>ABC</span></button>
                            <button role="button" type="button" aria-disabled="false" tabindex="-1" class="ui-keyboard-button ui-keyboard-accept ui-keyboard-widekey ui-keyboard-actionkey ui-state-default ui-corner-all ui-state-active" data-value="return" name="accept" data-pos="3,3" title="" data-action="accept" data-original="return" data-curtxt="return" data-curnum="0"><span>return</span></button>
                            <br class="ui-keyboard-button-endrow">
                          </div>
                        </div>